package control

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

type Migration struct {
	Version int
	Name    string
	SQL     string
}

var Migrations = []Migration{
	{
		Version: 1,
		Name:    "phase05_control_core",
		SQL: `
CREATE TABLE app_users (
    id uuid PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    role text NOT NULL CHECK (role IN ('admin', 'operator', 'viewer')),
    status text NOT NULL CHECK (status IN ('active', 'revoked')) DEFAULT 'active',
    force_password_change boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

CREATE TABLE user_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_sessions_user_id_idx ON user_sessions(user_id);
CREATE INDEX user_sessions_expires_at_idx ON user_sessions(expires_at);

CREATE TABLE agents (
    id uuid PRIMARY KEY,
    hostname text NOT NULL UNIQUE,
    kernel_version text NOT NULL DEFAULT '',
    ubuntu_version text NOT NULL DEFAULT '',
    xdp_mode text NOT NULL DEFAULT '',
    devmap_support boolean NOT NULL DEFAULT false,
    agent_version text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'registered',
    active_policy_version bigint NOT NULL DEFAULT 0,
    last_seen_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX agents_status_idx ON agents(status);
CREATE INDEX agents_last_seen_at_idx ON agents(last_seen_at);

CREATE TABLE agent_interfaces (
    id uuid PRIMARY KEY,
    agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    name text NOT NULL,
    ifindex integer NOT NULL DEFAULT 0,
    mac text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT '',
    link_speed_bps bigint NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (agent_id, name)
);

CREATE TABLE backend_services (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name text NOT NULL UNIQUE,
    description text NOT NULL DEFAULT '',
    backend_cidr inet NOT NULL,
    protocol text NOT NULL CHECK (protocol IN ('tcp', 'udp', 'icmp')),
    allowed_ports integer[] NOT NULL DEFAULT '{}',
    output_interface text NOT NULL,
    owner text NOT NULL,
    criticality text NOT NULL,
    protection_mode text NOT NULL CHECK (protection_mode IN ('observe', 'enforce')),
    enabled boolean NOT NULL DEFAULT true,
    priority integer NOT NULL DEFAULT 100,
    tags text[] NOT NULL DEFAULT '{}',
    sync_status text NOT NULL DEFAULT 'pending',
    resolved_ifindex integer NOT NULL DEFAULT 0,
    resolved_next_hop_mac text NOT NULL DEFAULT '',
    resolved_src_mac text NOT NULL DEFAULT '',
    neighbor_resolution_status text NOT NULL DEFAULT 'unresolved',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE INDEX backend_services_enabled_idx ON backend_services(enabled);
CREATE INDEX backend_services_backend_cidr_idx ON backend_services USING gist (backend_cidr inet_ops);

CREATE TABLE forwarding_policies (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id uuid NOT NULL REFERENCES backend_services(id) ON DELETE CASCADE,
    match_protocol text NOT NULL CHECK (match_protocol IN ('tcp', 'udp', 'icmp')),
    match_dst_port integer NOT NULL DEFAULT 0,
    backend_target inet NOT NULL,
    output_interface text NOT NULL,
    resolved_ifindex integer NOT NULL DEFAULT 0,
    resolved_dst_mac text NOT NULL DEFAULT '',
    resolved_src_mac text NOT NULL DEFAULT '',
    devmap_key integer NOT NULL DEFAULT 0,
    action text NOT NULL DEFAULT 'redirect',
    priority integer NOT NULL DEFAULT 100,
    enabled boolean NOT NULL DEFAULT true,
    owner text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX forwarding_policies_service_id_idx ON forwarding_policies(service_id);
CREATE UNIQUE INDEX forwarding_policies_match_unique_idx
    ON forwarding_policies(service_id, match_protocol, match_dst_port)
    WHERE enabled;

CREATE TABLE rules (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id uuid REFERENCES backend_services(id) ON DELETE SET NULL,
    name text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    match_expr jsonb NOT NULL DEFAULT '{}'::jsonb,
    action text NOT NULL CHECK (action IN ('observe', 'drop', 'rate_limit', 'sample')),
    mode text NOT NULL CHECK (mode IN ('observe', 'enforce')),
    threshold_pps bigint NOT NULL DEFAULT 0,
    threshold_bps bigint NOT NULL DEFAULT 0,
    threshold_cps bigint NOT NULL DEFAULT 0,
    burst_packets bigint NOT NULL DEFAULT 0,
    burst_bytes bigint NOT NULL DEFAULT 0,
    sample_denom integer NOT NULL DEFAULT 0,
    ttl_seconds integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    confidence numeric NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    owner text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX rules_service_id_idx ON rules(service_id);
CREATE INDEX rules_expires_at_idx ON rules(expires_at);

CREATE TABLE whitelist_entries (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ip_or_cidr inet NOT NULL,
    scope text NOT NULL CHECK (scope IN ('global', 'service')),
    service_id uuid REFERENCES backend_services(id) ON DELETE CASCADE,
    label text NOT NULL DEFAULT '',
    reason text NOT NULL,
    owner text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    expires_at timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX whitelist_entries_ip_idx ON whitelist_entries USING gist (ip_or_cidr inet_ops);
CREATE INDEX whitelist_entries_scope_idx ON whitelist_entries(scope, service_id);

CREATE TABLE manual_blacklist_entries (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ip_or_cidr inet NOT NULL,
    score integer NOT NULL DEFAULT 0,
    action text NOT NULL DEFAULT 'drop',
    source text NOT NULL DEFAULT 'manual',
    rule_id uuid REFERENCES rules(id) ON DELETE SET NULL,
    reason text NOT NULL,
    expires_at timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX manual_blacklist_entries_ip_idx ON manual_blacklist_entries USING gist (ip_or_cidr inet_ops);

CREATE TABLE feed_sources (
    id uuid PRIMARY KEY,
    name text NOT NULL UNIQUE,
    type text NOT NULL,
    url text NOT NULL DEFAULT '',
    credential_ref text NOT NULL DEFAULT '',
    required_for_production boolean NOT NULL DEFAULT false,
    enabled boolean NOT NULL DEFAULT false,
    interval_seconds integer NOT NULL DEFAULT 3600,
    license_note text NOT NULL DEFAULT '',
    quota_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'placeholder',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE policy_snapshots (
    version bigint PRIMARY KEY,
    checksum text NOT NULL,
    object_checksum text NOT NULL,
    snapshot jsonb NOT NULL,
    rollback_from bigint REFERENCES policy_snapshots(version),
    created_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX policy_snapshots_created_at_idx ON policy_snapshots(created_at);
CREATE INDEX policy_snapshots_rollback_from_idx ON policy_snapshots(rollback_from);

CREATE TABLE policy_apply_status (
    id uuid PRIMARY KEY,
    agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    policy_version bigint NOT NULL,
    status text NOT NULL,
    error_stage text NOT NULL DEFAULT '',
    error_reason text NOT NULL DEFAULT '',
    map_stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    devmap_stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    reported_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (agent_id, policy_version)
);
CREATE INDEX policy_apply_status_agent_idx ON policy_apply_status(agent_id, reported_at);

CREATE TABLE audit_events (
    id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor_id uuid REFERENCES app_users(id) ON DELETE SET NULL,
    actor_username text NOT NULL DEFAULT '',
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    before jsonb,
    after jsonb,
    reason text,
    request_id text NOT NULL DEFAULT '',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE audit_events_default PARTITION OF audit_events DEFAULT;
CREATE INDEX audit_events_actor_idx ON audit_events(actor_id, created_at);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type, entity_id, created_at);
`,
	},
	{
		Version: 2,
		Name:    "phase06_observability_events",
		SQL: `
CREATE TABLE security_events (
    id uuid PRIMARY KEY,
    received_at timestamptz NOT NULL DEFAULT now(),
    event_time timestamptz NOT NULL DEFAULT now(),
    agent_id uuid REFERENCES agents(id) ON DELETE SET NULL,
    mono_ts_ns bigint NOT NULL DEFAULT 0,
    policy_version bigint NOT NULL DEFAULT 0,
    src_ip inet NOT NULL,
    src_prefix24 inet NOT NULL,
    dst_ip inet NOT NULL,
    src_port integer NOT NULL DEFAULT 0,
    dst_port integer NOT NULL DEFAULT 0,
    protocol integer NOT NULL DEFAULT 0,
    tcp_flags integer NOT NULL DEFAULT 0,
    action integer NOT NULL DEFAULT 0,
    reason integer NOT NULL DEFAULT 0,
    service_id bigint NOT NULL DEFAULT 0,
    rule_id bigint NOT NULL DEFAULT 0,
    pkt_len integer NOT NULL DEFAULT 0,
    sample_rate integer NOT NULL DEFAULT 1,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX security_events_time_idx ON security_events(event_time DESC);
CREATE INDEX security_events_agent_time_idx ON security_events(agent_id, event_time DESC);
CREATE INDEX security_events_service_time_idx ON security_events(service_id, event_time DESC);
CREATE INDEX security_events_rule_time_idx ON security_events(rule_id, event_time DESC);
CREATE INDEX security_events_action_reason_time_idx ON security_events(action, reason, event_time DESC);
CREATE INDEX security_events_src_ip_time_idx ON security_events(src_ip, event_time DESC);
CREATE INDEX security_events_src_prefix24_time_idx ON security_events(src_prefix24, event_time DESC);
CREATE INDEX security_events_dst_port_time_idx ON security_events(dst_port, event_time DESC);
`,
	},
	{
		Version: 3,
		Name:    "phase07_baseline_anomaly_auto_enforce",
		SQL: `
ALTER TABLE rules
    ADD COLUMN IF NOT EXISTS dimension text NOT NULL DEFAULT 'source_service'
        CHECK (dimension IN ('source', 'service', 'source_service'));

CREATE TABLE baseline_profiles (
    id uuid PRIMARY KEY,
    service_id uuid NOT NULL REFERENCES backend_services(id) ON DELETE CASCADE,
    interface_name text NOT NULL,
    protocol text NOT NULL CHECK (protocol IN ('tcp', 'udp', 'icmp', 'all')),
    port integer NOT NULL DEFAULT 0,
    time_window text NOT NULL DEFAULT '5m',
    expected_pps double precision NOT NULL DEFAULT 0,
    expected_bps double precision NOT NULL DEFAULT 0,
    expected_cps double precision NOT NULL DEFAULT 0,
    history_hours integer NOT NULL DEFAULT 0,
    confidence numeric NOT NULL DEFAULT 0,
    approved boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'draft',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    approved_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    approved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (service_id, interface_name, protocol, port, time_window)
);
CREATE INDEX baseline_profiles_service_idx ON baseline_profiles(service_id, approved, time_window);

CREATE TABLE anomaly_evaluations (
    id uuid PRIMARY KEY,
    service_id uuid REFERENCES backend_services(id) ON DELETE SET NULL,
    baseline_id uuid REFERENCES baseline_profiles(id) ON DELETE SET NULL,
    evaluated_at timestamptz NOT NULL DEFAULT now(),
    time_window text NOT NULL DEFAULT '5m',
    pps double precision NOT NULL DEFAULT 0,
    bps double precision NOT NULL DEFAULT 0,
    cps double precision NOT NULL DEFAULT 0,
    drop_ratio double precision NOT NULL DEFAULT 0,
    score numeric NOT NULL DEFAULT 0,
    confidence numeric NOT NULL DEFAULT 0,
    signals text[] NOT NULL DEFAULT '{}',
    recommendation text NOT NULL DEFAULT 'observe',
    recommended_action text NOT NULL DEFAULT 'rate_limit',
    proposed_ttl_seconds integer NOT NULL DEFAULT 0,
    proposed_rule_id uuid REFERENCES rules(id) ON DELETE SET NULL,
    auto_enforced boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'recorded',
    reason text NOT NULL DEFAULT '',
    source text NOT NULL DEFAULT '',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX anomaly_evaluations_time_idx ON anomaly_evaluations(evaluated_at DESC);
CREATE INDEX anomaly_evaluations_service_time_idx ON anomaly_evaluations(service_id, evaluated_at DESC);
`,
	},
	{
		Version: 4,
		Name:    "phase08_threat_feed_sync",
		SQL: `
ALTER TABLE feed_sources
    ADD COLUMN IF NOT EXISTS last_success_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_error_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_error text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS next_run_at timestamptz,
    ADD COLUMN IF NOT EXISTS active_entries integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS conflict_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS parse_error_count integer NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS feed_sources_enabled_next_run_idx ON feed_sources(enabled, next_run_at);

CREATE TABLE feed_runs (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES feed_sources(id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL DEFAULT 'running',
    items_fetched integer NOT NULL DEFAULT 0,
    items_valid integer NOT NULL DEFAULT 0,
    parse_errors integer NOT NULL DEFAULT 0,
    error text NOT NULL DEFAULT '',
    snapshot_version bigint NOT NULL DEFAULT 0
);
CREATE INDEX feed_runs_source_started_idx ON feed_runs(source_id, started_at DESC);
CREATE INDEX feed_runs_status_started_idx ON feed_runs(status, started_at DESC);

CREATE TABLE reputation_entries (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    source_id uuid NOT NULL REFERENCES feed_sources(id) ON DELETE CASCADE,
    ip_or_cidr inet NOT NULL,
    score integer NOT NULL DEFAULT 0,
    action text NOT NULL DEFAULT 'drop',
    reason text NOT NULL DEFAULT '',
    ttl_seconds integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    status text NOT NULL DEFAULT 'active',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reputation_entries_source_status_idx ON reputation_entries(source_id, status);
CREATE INDEX reputation_entries_ip_idx ON reputation_entries USING gist (ip_or_cidr inet_ops);
CREATE UNIQUE INDEX reputation_entries_source_cidr_unique_idx ON reputation_entries(source_id, ip_or_cidr, action, score, ttl_seconds);

CREATE TABLE feed_conflicts (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES feed_sources(id) ON DELETE CASCADE,
    reputation_id uuid NOT NULL REFERENCES reputation_entries(id) ON DELETE CASCADE,
    whitelist_id uuid NOT NULL REFERENCES whitelist_entries(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'active',
    detected_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    UNIQUE (reputation_id, whitelist_id)
);
CREATE INDEX feed_conflicts_source_status_idx ON feed_conflicts(source_id, status);
CREATE INDEX feed_conflicts_whitelist_idx ON feed_conflicts(whitelist_id, status);
`,
	},
	{
		Version: 5,
		Name:    "phase09_telegram_isp_runbook",
		SQL: `
CREATE TABLE telegram_configs (
    id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    bot_token_ref text NOT NULL DEFAULT '',
    chat_id text NOT NULL DEFAULT '',
    parse_mode text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alert_policies (
    id uuid PRIMARY KEY,
    alert_type text NOT NULL,
    severity text NOT NULL,
    channel text NOT NULL DEFAULT 'telegram',
    rate_limit_seconds integer NOT NULL DEFAULT 300,
    max_attempts integer NOT NULL DEFAULT 3,
    template text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (alert_type, severity, channel)
);
CREATE INDEX alert_policies_enabled_idx ON alert_policies(enabled, alert_type, severity);

CREATE TABLE alerts (
    id uuid PRIMARY KEY,
    severity text NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    type text NOT NULL,
    dedupe_key text NOT NULL,
    service_id uuid REFERENCES backend_services(id) ON DELETE SET NULL,
    affected_service text NOT NULL DEFAULT '',
    vector text NOT NULL DEFAULT '',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    recommended_action text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending',
    created_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz
);
CREATE INDEX alerts_dedupe_created_idx ON alerts(dedupe_key, created_at DESC);
CREATE INDEX alerts_status_created_idx ON alerts(status, created_at DESC);
CREATE INDEX alerts_type_severity_idx ON alerts(type, severity);

CREATE TABLE alert_deliveries (
    id uuid PRIMARY KEY,
    alert_id uuid NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    channel text NOT NULL DEFAULT 'telegram',
    status text NOT NULL,
    attempt integer NOT NULL DEFAULT 0,
    error text NOT NULL DEFAULT '',
    response jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    sent_at timestamptz
);
CREATE INDEX alert_deliveries_alert_idx ON alert_deliveries(alert_id, created_at);
CREATE INDEX alert_deliveries_status_idx ON alert_deliveries(status, created_at DESC);
`,
	},
	{
		Version: 6,
		Name:    "udp_source_port_blocks",
		SQL: `
CREATE TABLE IF NOT EXISTS udp_source_port_blocks (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    port integer NOT NULL UNIQUE CHECK (port >= 0 AND port <= 65535),
    label text NOT NULL DEFAULT '',
    reason text NOT NULL,
    owner text NOT NULL,
    expires_at timestamptz,
    enabled boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS udp_source_port_blocks_enabled_idx ON udp_source_port_blocks(enabled);
CREATE INDEX IF NOT EXISTS udp_source_port_blocks_expires_at_idx ON udp_source_port_blocks(expires_at);

INSERT INTO udp_source_port_blocks(id, port, label, reason, owner, enabled) VALUES
('00000000-0000-4000-8000-000000000001', 0, 'reserved source port', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000002', 19, 'CHARGEN', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000003', 53, 'DNS', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000004', 69, 'TFTP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000005', 111, 'SunRPC', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000006', 123, 'NTP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000007', 137, 'NetBIOS', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000008', 161, 'SNMP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000009', 162, 'SNMP trap', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000a', 389, 'CLDAP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000b', 427, 'SLP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000c', 520, 'RIP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000d', 1194, 'OpenVPN', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000e', 1900, 'SSDP', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-00000000000f', 3702, 'WS-Discovery', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000010', 5353, 'mDNS', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000011', 10001, 'Ubiquiti discovery', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000012', 11211, 'Memcached', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000013', 20800, 'Call of Duty', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false),
('00000000-0000-4000-8000-000000000014', 27005, 'SRCDS', 'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance', 'system', false)
ON CONFLICT (port) DO NOTHING;
`,
	},
	{
		Version: 7,
		Name:    "multi_tenant_rbac",
		SQL: `
CREATE TABLE IF NOT EXISTS tenants (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'revoked')) DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO tenants(id, slug, name, status)
VALUES ('00000000-0000-4000-8000-000000001000', 'default', 'Default Tenant', 'active')
ON CONFLICT (slug) DO NOTHING;

ALTER TABLE app_users
    ADD COLUMN IF NOT EXISTS platform_role text NOT NULL DEFAULT '';

UPDATE app_users SET platform_role='platform_admin' WHERE role='admin' AND platform_role='';

ALTER TABLE user_sessions
    ADD COLUMN IF NOT EXISTS active_tenant_id uuid REFERENCES tenants(id);

CREATE TABLE IF NOT EXISTS tenant_memberships (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('admin', 'operator', 'viewer')),
    status text NOT NULL CHECK (status IN ('active', 'revoked')) DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id)
);
CREATE INDEX IF NOT EXISTS tenant_memberships_user_idx ON tenant_memberships(user_id, status);
CREATE INDEX IF NOT EXISTS tenant_memberships_tenant_role_idx ON tenant_memberships(tenant_id, role, status);

INSERT INTO tenant_memberships(id, tenant_id, user_id, role, status)
SELECT u.id, t.id, u.id, u.role, u.status
FROM app_users u
CROSS JOIN tenants t
WHERE t.slug='default'
ON CONFLICT (tenant_id, user_id) DO NOTHING;

UPDATE user_sessions SET active_tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE active_tenant_id IS NULL;

ALTER TABLE agents ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE agent_interfaces ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE backend_services ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE forwarding_policies ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE rules ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE whitelist_entries ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE manual_blacklist_entries ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE feed_sources ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE feed_runs ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE reputation_entries ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE feed_conflicts ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE policy_snapshots ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE policy_apply_status ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE security_events ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE baseline_profiles ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE anomaly_evaluations ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE telegram_configs ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE alert_policies ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE alert_deliveries ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE udp_source_port_blocks ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS tenant_id uuid;

UPDATE agents SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE agent_interfaces ai SET tenant_id=a.tenant_id FROM agents a WHERE ai.agent_id=a.id AND ai.tenant_id IS NULL;
UPDATE agent_interfaces SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE backend_services SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE forwarding_policies fp SET tenant_id=bs.tenant_id FROM backend_services bs WHERE fp.service_id=bs.id AND fp.tenant_id IS NULL;
UPDATE forwarding_policies SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE rules r SET tenant_id=bs.tenant_id FROM backend_services bs WHERE r.service_id=bs.id AND r.tenant_id IS NULL;
UPDATE rules SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE whitelist_entries w SET tenant_id=bs.tenant_id FROM backend_services bs WHERE w.service_id=bs.id AND w.tenant_id IS NULL;
UPDATE whitelist_entries SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE manual_blacklist_entries b SET tenant_id=r.tenant_id FROM rules r WHERE b.rule_id=r.id AND b.tenant_id IS NULL;
UPDATE manual_blacklist_entries SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE feed_sources SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE feed_runs fr SET tenant_id=fs.tenant_id FROM feed_sources fs WHERE fr.source_id=fs.id AND fr.tenant_id IS NULL;
UPDATE feed_runs SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE reputation_entries re SET tenant_id=fs.tenant_id FROM feed_sources fs WHERE re.source_id=fs.id AND re.tenant_id IS NULL;
UPDATE reputation_entries SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE feed_conflicts fc SET tenant_id=fs.tenant_id FROM feed_sources fs WHERE fc.source_id=fs.id AND fc.tenant_id IS NULL;
UPDATE feed_conflicts SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE policy_snapshots SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE policy_apply_status pas SET tenant_id=a.tenant_id FROM agents a WHERE pas.agent_id=a.id AND pas.tenant_id IS NULL;
UPDATE policy_apply_status SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE security_events se SET tenant_id=a.tenant_id FROM agents a WHERE se.agent_id=a.id AND se.tenant_id IS NULL;
UPDATE security_events SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE baseline_profiles bp SET tenant_id=bs.tenant_id FROM backend_services bs WHERE bp.service_id=bs.id AND bp.tenant_id IS NULL;
UPDATE baseline_profiles SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE anomaly_evaluations ae SET tenant_id=bs.tenant_id FROM backend_services bs WHERE ae.service_id=bs.id AND ae.tenant_id IS NULL;
UPDATE anomaly_evaluations SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE telegram_configs SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE alert_policies SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE alerts a SET tenant_id=bs.tenant_id FROM backend_services bs WHERE a.service_id=bs.id AND a.tenant_id IS NULL;
UPDATE alerts SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE alert_deliveries ad SET tenant_id=a.tenant_id FROM alerts a WHERE ad.alert_id=a.id AND ad.tenant_id IS NULL;
UPDATE alert_deliveries SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE udp_source_port_blocks SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;
UPDATE audit_events SET tenant_id=(SELECT id FROM tenants WHERE slug='default') WHERE tenant_id IS NULL;

ALTER TABLE agents ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE agent_interfaces ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE backend_services ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE forwarding_policies ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE rules ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE whitelist_entries ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE manual_blacklist_entries ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE feed_sources ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE feed_runs ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE reputation_entries ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE feed_conflicts ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE policy_snapshots ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE policy_apply_status ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE security_events ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE baseline_profiles ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE anomaly_evaluations ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE telegram_configs ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE alert_policies ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE alerts ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE alert_deliveries ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE udp_source_port_blocks ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE audit_events ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE agents DROP CONSTRAINT IF EXISTS agents_hostname_key;
CREATE UNIQUE INDEX IF NOT EXISTS agents_tenant_hostname_unique_idx ON agents(tenant_id, hostname);
ALTER TABLE backend_services DROP CONSTRAINT IF EXISTS backend_services_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS backend_services_tenant_name_unique_idx ON backend_services(tenant_id, name);
ALTER TABLE feed_sources DROP CONSTRAINT IF EXISTS feed_sources_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS feed_sources_tenant_name_unique_idx ON feed_sources(tenant_id, name);
ALTER TABLE udp_source_port_blocks DROP CONSTRAINT IF EXISTS udp_source_port_blocks_port_key;
CREATE UNIQUE INDEX IF NOT EXISTS udp_source_port_blocks_tenant_port_unique_idx ON udp_source_port_blocks(tenant_id, port);
ALTER TABLE alert_policies DROP CONSTRAINT IF EXISTS alert_policies_alert_type_severity_channel_key;
CREATE UNIQUE INDEX IF NOT EXISTS alert_policies_tenant_type_severity_channel_unique_idx ON alert_policies(tenant_id, alert_type, severity, channel);

ALTER TABLE policy_snapshots DROP CONSTRAINT IF EXISTS policy_snapshots_rollback_from_fkey;
ALTER TABLE policy_snapshots DROP CONSTRAINT IF EXISTS policy_snapshots_pkey;
ALTER TABLE policy_snapshots ADD PRIMARY KEY (tenant_id, version);

ALTER TABLE telegram_configs DROP CONSTRAINT IF EXISTS telegram_configs_pkey;
ALTER TABLE telegram_configs ADD PRIMARY KEY (tenant_id, id);

CREATE INDEX IF NOT EXISTS agents_tenant_idx ON agents(tenant_id, status);
CREATE INDEX IF NOT EXISTS agent_interfaces_tenant_idx ON agent_interfaces(tenant_id, agent_id);
CREATE INDEX IF NOT EXISTS backend_services_tenant_idx ON backend_services(tenant_id, enabled);
CREATE INDEX IF NOT EXISTS forwarding_policies_tenant_idx ON forwarding_policies(tenant_id, service_id);
CREATE INDEX IF NOT EXISTS rules_tenant_idx ON rules(tenant_id, service_id);
CREATE INDEX IF NOT EXISTS whitelist_entries_tenant_idx ON whitelist_entries(tenant_id, scope, service_id);
CREATE INDEX IF NOT EXISTS manual_blacklist_entries_tenant_idx ON manual_blacklist_entries(tenant_id, rule_id);
CREATE INDEX IF NOT EXISTS feed_sources_tenant_idx ON feed_sources(tenant_id, enabled, next_run_at);
CREATE INDEX IF NOT EXISTS feed_runs_tenant_idx ON feed_runs(tenant_id, source_id, started_at DESC);
CREATE INDEX IF NOT EXISTS reputation_entries_tenant_idx ON reputation_entries(tenant_id, source_id, status);
CREATE INDEX IF NOT EXISTS policy_snapshots_tenant_created_idx ON policy_snapshots(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS policy_apply_status_tenant_idx ON policy_apply_status(tenant_id, agent_id, reported_at DESC);
CREATE INDEX IF NOT EXISTS security_events_tenant_time_idx ON security_events(tenant_id, event_time DESC);
CREATE INDEX IF NOT EXISTS baseline_profiles_tenant_idx ON baseline_profiles(tenant_id, service_id, approved, time_window);
CREATE INDEX IF NOT EXISTS anomaly_evaluations_tenant_idx ON anomaly_evaluations(tenant_id, evaluated_at DESC);
CREATE INDEX IF NOT EXISTS alerts_tenant_idx ON alerts(tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS alert_deliveries_tenant_idx ON alert_deliveries(tenant_id, alert_id, created_at);
CREATE INDEX IF NOT EXISTS audit_events_tenant_idx ON audit_events(tenant_id, created_at DESC);

DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'agents',
        'agent_interfaces',
        'backend_services',
        'forwarding_policies',
        'rules',
        'whitelist_entries',
        'manual_blacklist_entries',
        'feed_sources',
        'feed_runs',
        'reputation_entries',
        'feed_conflicts',
        'policy_snapshots',
        'policy_apply_status',
        'security_events',
        'baseline_profiles',
        'anomaly_evaluations',
        'telegram_configs',
        'alert_policies',
        'alerts',
        'alert_deliveries',
        'udp_source_port_blocks',
        'audit_events'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', table_name);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I FOR ALL USING (tenant_id = NULLIF(current_setting(''anti_ddos.tenant_id'', true), '''')::uuid OR current_setting(''anti_ddos.platform'', true) = ''true'') WITH CHECK (tenant_id = NULLIF(current_setting(''anti_ddos.tenant_id'', true), '''')::uuid OR current_setting(''anti_ddos.platform'', true) = ''true'')',
            table_name
        );
    END LOOP;
END $$;
	`,
	},
	{
		Version: 8,
		Name:    "operator_single_tenant",
		SQL: `
	DO $$
	DECLARE
	    violation_count integer;
	BEGIN
	    SELECT count(*) INTO violation_count
	    FROM (
	        SELECT m.user_id
	        FROM tenant_memberships m
	        JOIN app_users u ON u.id = m.user_id
	        WHERE m.status='active'
	          AND COALESCE(u.platform_role, '') <> 'platform_admin'
	        GROUP BY m.user_id
	        HAVING BOOL_OR(m.role='operator') AND COUNT(*) > 1
	    ) violations;
	    IF violation_count > 0 THEN
	        RAISE EXCEPTION 'operator_single_tenant migration blocked: % non-platform operator users have multiple active tenant memberships', violation_count;
	    END IF;
	END $$;

	CREATE OR REPLACE FUNCTION enforce_operator_single_tenant_membership()
	RETURNS trigger AS $$
	DECLARE
	    is_platform_admin boolean;
	    active_count bigint;
	    has_operator boolean;
	BEGIN
	    IF NEW.status <> 'active' THEN
	        RETURN NEW;
	    END IF;

	    SELECT COALESCE(platform_role, '') = 'platform_admin'
	    INTO is_platform_admin
	    FROM app_users
	    WHERE id = NEW.user_id;

	    IF COALESCE(is_platform_admin, false) THEN
	        RETURN NEW;
	    END IF;

	    SELECT COUNT(*), COALESCE(BOOL_OR(role='operator'), false)
	    INTO active_count, has_operator
	    FROM tenant_memberships
	    WHERE user_id = NEW.user_id
	      AND status = 'active';

	    IF has_operator AND active_count > 1 THEN
	        RAISE EXCEPTION 'operator identity cannot have active memberships in multiple tenants';
	    END IF;

	    RETURN NEW;
	END;
	$$ LANGUAGE plpgsql;

	DROP TRIGGER IF EXISTS tenant_memberships_operator_single_tenant ON tenant_memberships;
	CREATE TRIGGER tenant_memberships_operator_single_tenant
	AFTER INSERT OR UPDATE OF tenant_id, user_id, role, status ON tenant_memberships
	FOR EACH ROW
	EXECUTE FUNCTION enforce_operator_single_tenant_membership();
	`,
	},
	{
		Version: 9,
		Name:    "owner_user_rbac_no_tenant",
		SQL: `
DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'agents',
        'agent_interfaces',
        'backend_services',
        'forwarding_policies',
        'rules',
        'whitelist_entries',
        'manual_blacklist_entries',
        'feed_sources',
        'feed_runs',
        'reputation_entries',
        'feed_conflicts',
        'policy_snapshots',
        'policy_apply_status',
        'security_events',
        'baseline_profiles',
        'anomaly_evaluations',
        'telegram_configs',
        'alert_policies',
        'alerts',
        'alert_deliveries',
        'udp_source_port_blocks',
        'audit_events'
    ]
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', table_name);
        EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
    END LOOP;
END $$;

TRUNCATE TABLE
    alert_deliveries,
    alerts,
    alert_policies,
    telegram_configs,
    anomaly_evaluations,
    baseline_profiles,
    security_events,
    policy_apply_status,
    policy_snapshots,
    feed_conflicts,
    reputation_entries,
    feed_runs,
    feed_sources,
    manual_blacklist_entries,
    whitelist_entries,
    rules,
    forwarding_policies,
    backend_services,
    agent_interfaces,
    agents,
    udp_source_port_blocks,
    audit_events
RESTART IDENTITY CASCADE;

ALTER TABLE app_users DROP CONSTRAINT IF EXISTS app_users_role_check;
UPDATE app_users SET role = CASE WHEN role = 'admin' THEN 'admin' ELSE 'user' END;
ALTER TABLE app_users ADD CONSTRAINT app_users_role_check CHECK (role IN ('admin', 'user'));
ALTER TABLE app_users DROP COLUMN IF EXISTS platform_role;

ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS view_owner_user_id uuid REFERENCES app_users(id) ON DELETE SET NULL;
UPDATE user_sessions SET revoked_at=now() WHERE revoked_at IS NULL;
ALTER TABLE user_sessions DROP COLUMN IF EXISTS active_tenant_id;

DROP TRIGGER IF EXISTS tenant_memberships_operator_single_tenant ON tenant_memberships;
DROP FUNCTION IF EXISTS enforce_operator_single_tenant_membership();
DROP TABLE IF EXISTS tenant_memberships;
DROP TABLE IF EXISTS tenants;

DROP INDEX IF EXISTS agents_tenant_hostname_unique_idx;
DROP INDEX IF EXISTS backend_services_tenant_name_unique_idx;
DROP INDEX IF EXISTS feed_sources_tenant_name_unique_idx;
DROP INDEX IF EXISTS udp_source_port_blocks_tenant_port_unique_idx;
DROP INDEX IF EXISTS alert_policies_tenant_type_severity_channel_unique_idx;
DROP INDEX IF EXISTS agents_tenant_idx;
DROP INDEX IF EXISTS agent_interfaces_tenant_idx;
DROP INDEX IF EXISTS backend_services_tenant_idx;
DROP INDEX IF EXISTS forwarding_policies_tenant_idx;
DROP INDEX IF EXISTS rules_tenant_idx;
DROP INDEX IF EXISTS whitelist_entries_tenant_idx;
DROP INDEX IF EXISTS manual_blacklist_entries_tenant_idx;
DROP INDEX IF EXISTS feed_sources_tenant_idx;
DROP INDEX IF EXISTS feed_runs_tenant_idx;
DROP INDEX IF EXISTS reputation_entries_tenant_idx;
DROP INDEX IF EXISTS policy_snapshots_tenant_created_idx;
DROP INDEX IF EXISTS policy_apply_status_tenant_idx;
DROP INDEX IF EXISTS security_events_tenant_time_idx;
DROP INDEX IF EXISTS baseline_profiles_tenant_idx;
DROP INDEX IF EXISTS anomaly_evaluations_tenant_idx;
DROP INDEX IF EXISTS alerts_tenant_idx;
DROP INDEX IF EXISTS alert_deliveries_tenant_idx;
DROP INDEX IF EXISTS audit_events_tenant_idx;

ALTER TABLE policy_snapshots DROP CONSTRAINT IF EXISTS policy_snapshots_pkey;
ALTER TABLE telegram_configs DROP CONSTRAINT IF EXISTS telegram_configs_pkey;

ALTER TABLE agents ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE agent_interfaces ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE backend_services ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE forwarding_policies ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE rules ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE whitelist_entries ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE manual_blacklist_entries ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE feed_sources ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE feed_runs ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE reputation_entries ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE feed_conflicts ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE policy_snapshots ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE policy_apply_status ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE security_events ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE baseline_profiles ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE anomaly_evaluations ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE telegram_configs ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE alert_policies ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE alert_deliveries ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE udp_source_port_blocks ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS owner_user_id uuid REFERENCES app_users(id) ON DELETE SET NULL;

ALTER TABLE agents ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE agent_interfaces ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE backend_services ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE forwarding_policies ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE rules ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE whitelist_entries ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE manual_blacklist_entries ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE feed_sources ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE feed_runs ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE reputation_entries ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE feed_conflicts ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE policy_snapshots ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE policy_apply_status ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE security_events ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE baseline_profiles ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE anomaly_evaluations ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE telegram_configs ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE alert_policies ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE alerts ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE alert_deliveries ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE udp_source_port_blocks ALTER COLUMN owner_user_id SET NOT NULL;

ALTER TABLE agents DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE agent_interfaces DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE backend_services DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE forwarding_policies DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE rules DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE whitelist_entries DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE manual_blacklist_entries DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE feed_sources DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE feed_runs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE reputation_entries DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE feed_conflicts DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE policy_snapshots DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE policy_apply_status DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE security_events DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE baseline_profiles DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE anomaly_evaluations DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE telegram_configs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE alert_policies DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE alerts DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE alert_deliveries DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE udp_source_port_blocks DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE audit_events DROP COLUMN IF EXISTS tenant_id;

CREATE UNIQUE INDEX IF NOT EXISTS agents_owner_hostname_unique_idx ON agents(owner_user_id, hostname);
CREATE UNIQUE INDEX IF NOT EXISTS backend_services_owner_name_unique_idx ON backend_services(owner_user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS feed_sources_owner_name_unique_idx ON feed_sources(owner_user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS udp_source_port_blocks_owner_port_unique_idx ON udp_source_port_blocks(owner_user_id, port);
CREATE UNIQUE INDEX IF NOT EXISTS alert_policies_owner_type_severity_channel_unique_idx ON alert_policies(owner_user_id, alert_type, severity, channel);

WITH seed(port, label) AS (
    VALUES
    (0, 'reserved source port'),
    (19, 'CHARGEN'),
    (53, 'DNS'),
    (69, 'TFTP'),
    (111, 'SunRPC'),
    (123, 'NTP'),
    (137, 'NetBIOS'),
    (161, 'SNMP'),
    (162, 'SNMP trap'),
    (389, 'CLDAP'),
    (427, 'SLP'),
    (520, 'RIP'),
    (1194, 'OpenVPN'),
    (1900, 'SSDP'),
    (3702, 'WS-Discovery'),
    (5353, 'mDNS'),
    (10001, 'Ubiquiti discovery'),
    (11211, 'Memcached'),
    (20800, 'Call of Duty'),
    (27005, 'SRCDS')
)
INSERT INTO udp_source_port_blocks(id, owner_user_id, port, label, reason, owner, enabled)
SELECT (
        substr(h.hash, 1, 8) || '-' ||
        substr(h.hash, 9, 4) || '-' ||
        substr(h.hash, 13, 4) || '-' ||
        substr(h.hash, 17, 4) || '-' ||
        substr(h.hash, 21, 12)
    )::uuid,
    u.id,
    seed.port,
    seed.label,
    'seeded UDP reflection source-port candidate from CISA/Cloudflare guidance',
    'system',
    false
FROM app_users u
CROSS JOIN seed
CROSS JOIN LATERAL (SELECT md5(u.id::text || ':' || seed.port::text) AS hash) h
WHERE u.role='user' AND u.status='active'
ON CONFLICT (owner_user_id, port) DO NOTHING;

ALTER TABLE policy_snapshots ADD PRIMARY KEY (owner_user_id, version);
ALTER TABLE telegram_configs ADD PRIMARY KEY (owner_user_id, id);

CREATE INDEX IF NOT EXISTS user_sessions_view_owner_user_idx ON user_sessions(view_owner_user_id);
CREATE INDEX IF NOT EXISTS agents_owner_idx ON agents(owner_user_id, status);
CREATE INDEX IF NOT EXISTS agent_interfaces_owner_idx ON agent_interfaces(owner_user_id, agent_id);
CREATE INDEX IF NOT EXISTS backend_services_owner_idx ON backend_services(owner_user_id, enabled);
CREATE INDEX IF NOT EXISTS forwarding_policies_owner_idx ON forwarding_policies(owner_user_id, service_id);
CREATE INDEX IF NOT EXISTS rules_owner_idx ON rules(owner_user_id, service_id);
CREATE INDEX IF NOT EXISTS whitelist_entries_owner_idx ON whitelist_entries(owner_user_id, scope, service_id);
CREATE INDEX IF NOT EXISTS manual_blacklist_entries_owner_idx ON manual_blacklist_entries(owner_user_id, rule_id);
CREATE INDEX IF NOT EXISTS feed_sources_owner_idx ON feed_sources(owner_user_id, enabled, next_run_at);
CREATE INDEX IF NOT EXISTS feed_runs_owner_idx ON feed_runs(owner_user_id, source_id, started_at DESC);
CREATE INDEX IF NOT EXISTS reputation_entries_owner_idx ON reputation_entries(owner_user_id, source_id, status);
CREATE INDEX IF NOT EXISTS policy_snapshots_owner_created_idx ON policy_snapshots(owner_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS policy_apply_status_owner_idx ON policy_apply_status(owner_user_id, agent_id, reported_at DESC);
CREATE INDEX IF NOT EXISTS security_events_owner_time_idx ON security_events(owner_user_id, event_time DESC);
CREATE INDEX IF NOT EXISTS baseline_profiles_owner_idx ON baseline_profiles(owner_user_id, service_id, approved, time_window);
CREATE INDEX IF NOT EXISTS anomaly_evaluations_owner_idx ON anomaly_evaluations(owner_user_id, evaluated_at DESC);
CREATE INDEX IF NOT EXISTS alerts_owner_idx ON alerts(owner_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS alert_deliveries_owner_idx ON alert_deliveries(owner_user_id, alert_id, created_at);
CREATE INDEX IF NOT EXISTS audit_events_owner_idx ON audit_events(owner_user_id, created_at DESC);
	`,
	},
	{
		Version: 10,
		Name:    "global_admin_threat_feed",
		SQL: `
ALTER TABLE feed_sources ALTER COLUMN owner_user_id DROP NOT NULL;
ALTER TABLE feed_runs ALTER COLUMN owner_user_id DROP NOT NULL;
ALTER TABLE reputation_entries ALTER COLUMN owner_user_id DROP NOT NULL;

DROP INDEX IF EXISTS feed_sources_owner_name_unique_idx;
CREATE UNIQUE INDEX IF NOT EXISTS feed_sources_global_name_unique_idx ON feed_sources(LOWER(name)) WHERE owner_user_id IS NULL;

CREATE INDEX IF NOT EXISTS feed_sources_global_enabled_idx ON feed_sources(enabled, next_run_at) WHERE owner_user_id IS NULL;
CREATE INDEX IF NOT EXISTS feed_runs_global_started_idx ON feed_runs(source_id, started_at DESC) WHERE owner_user_id IS NULL;
CREATE INDEX IF NOT EXISTS reputation_entries_global_source_status_idx ON reputation_entries(source_id, status) WHERE owner_user_id IS NULL;
	`,
	},
}

func RunMigrations(ctx context.Context, pool *pgxpool.Pool) error {
	if pool == nil {
		return fmt.Errorf("nil pgx pool")
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
    version integer PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now()
)`); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(4100550005)`); err != nil {
		return err
	}
	for _, migration := range Migrations {
		var applied bool
		if err := tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE version = $1)`, migration.Version).Scan(&applied); err != nil {
			return err
		}
		if applied {
			continue
		}
		if _, err := tx.Exec(ctx, migration.SQL); err != nil {
			return fmt.Errorf("migration %d %s: %w", migration.Version, migration.Name, err)
		}
		if _, err := tx.Exec(ctx, `INSERT INTO schema_migrations(version, name) VALUES ($1, $2)`, migration.Version, migration.Name); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}

func AppliedMigrationNames(ctx context.Context, pool *pgxpool.Pool) ([]string, error) {
	rows, err := pool.Query(ctx, `SELECT name FROM schema_migrations ORDER BY version`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		out = append(out, name)
	}
	return out, rows.Err()
}

func SQLMigrationText() string {
	var b strings.Builder
	for _, migration := range Migrations {
		fmt.Fprintf(&b, "-- %03d_%s\n%s\n", migration.Version, migration.Name, migration.SQL)
	}
	return b.String()
}
