package control

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

type Migration struct {
	Version int
	Name    string
	SQL     string
}

var Migrations = []Migration{
	{
		Version: 1,
		Name:    "phase05_control_core",
		SQL: `
CREATE TABLE app_users (
    id uuid PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    role text NOT NULL CHECK (role IN ('admin', 'operator', 'viewer')),
    status text NOT NULL CHECK (status IN ('active', 'revoked')) DEFAULT 'active',
    force_password_change boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

CREATE TABLE user_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_sessions_user_id_idx ON user_sessions(user_id);
CREATE INDEX user_sessions_expires_at_idx ON user_sessions(expires_at);

CREATE TABLE agents (
    id uuid PRIMARY KEY,
    hostname text NOT NULL UNIQUE,
    kernel_version text NOT NULL DEFAULT '',
    ubuntu_version text NOT NULL DEFAULT '',
    xdp_mode text NOT NULL DEFAULT '',
    devmap_support boolean NOT NULL DEFAULT false,
    agent_version text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'registered',
    active_policy_version bigint NOT NULL DEFAULT 0,
    last_seen_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX agents_status_idx ON agents(status);
CREATE INDEX agents_last_seen_at_idx ON agents(last_seen_at);

CREATE TABLE agent_interfaces (
    id uuid PRIMARY KEY,
    agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    name text NOT NULL,
    ifindex integer NOT NULL DEFAULT 0,
    mac text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT '',
    link_speed_bps bigint NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (agent_id, name)
);

CREATE TABLE backend_services (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name text NOT NULL UNIQUE,
    description text NOT NULL DEFAULT '',
    backend_cidr inet NOT NULL,
    protocol text NOT NULL CHECK (protocol IN ('tcp', 'udp', 'icmp')),
    allowed_ports integer[] NOT NULL DEFAULT '{}',
    output_interface text NOT NULL,
    owner text NOT NULL,
    criticality text NOT NULL,
    protection_mode text NOT NULL CHECK (protection_mode IN ('observe', 'enforce')),
    enabled boolean NOT NULL DEFAULT true,
    priority integer NOT NULL DEFAULT 100,
    tags text[] NOT NULL DEFAULT '{}',
    sync_status text NOT NULL DEFAULT 'pending',
    resolved_ifindex integer NOT NULL DEFAULT 0,
    resolved_next_hop_mac text NOT NULL DEFAULT '',
    resolved_src_mac text NOT NULL DEFAULT '',
    neighbor_resolution_status text NOT NULL DEFAULT 'unresolved',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE INDEX backend_services_enabled_idx ON backend_services(enabled);
CREATE INDEX backend_services_backend_cidr_idx ON backend_services USING gist (backend_cidr inet_ops);

CREATE TABLE forwarding_policies (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id uuid NOT NULL REFERENCES backend_services(id) ON DELETE CASCADE,
    match_protocol text NOT NULL CHECK (match_protocol IN ('tcp', 'udp', 'icmp')),
    match_dst_port integer NOT NULL DEFAULT 0,
    backend_target inet NOT NULL,
    output_interface text NOT NULL,
    resolved_ifindex integer NOT NULL DEFAULT 0,
    resolved_dst_mac text NOT NULL DEFAULT '',
    resolved_src_mac text NOT NULL DEFAULT '',
    devmap_key integer NOT NULL DEFAULT 0,
    action text NOT NULL DEFAULT 'redirect',
    priority integer NOT NULL DEFAULT 100,
    enabled boolean NOT NULL DEFAULT true,
    owner text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX forwarding_policies_service_id_idx ON forwarding_policies(service_id);
CREATE UNIQUE INDEX forwarding_policies_match_unique_idx
    ON forwarding_policies(service_id, match_protocol, match_dst_port)
    WHERE enabled;

CREATE TABLE rules (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id uuid REFERENCES backend_services(id) ON DELETE SET NULL,
    name text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    match_expr jsonb NOT NULL DEFAULT '{}'::jsonb,
    action text NOT NULL CHECK (action IN ('observe', 'drop', 'rate_limit', 'sample')),
    mode text NOT NULL CHECK (mode IN ('observe', 'enforce')),
    threshold_pps bigint NOT NULL DEFAULT 0,
    threshold_bps bigint NOT NULL DEFAULT 0,
    threshold_cps bigint NOT NULL DEFAULT 0,
    burst_packets bigint NOT NULL DEFAULT 0,
    burst_bytes bigint NOT NULL DEFAULT 0,
    sample_denom integer NOT NULL DEFAULT 0,
    ttl_seconds integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    confidence numeric NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    owner text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX rules_service_id_idx ON rules(service_id);
CREATE INDEX rules_expires_at_idx ON rules(expires_at);

CREATE TABLE whitelist_entries (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ip_or_cidr inet NOT NULL,
    scope text NOT NULL CHECK (scope IN ('global', 'service')),
    service_id uuid REFERENCES backend_services(id) ON DELETE CASCADE,
    label text NOT NULL DEFAULT '',
    reason text NOT NULL,
    owner text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    expires_at timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX whitelist_entries_ip_idx ON whitelist_entries USING gist (ip_or_cidr inet_ops);
CREATE INDEX whitelist_entries_scope_idx ON whitelist_entries(scope, service_id);

CREATE TABLE manual_blacklist_entries (
    id uuid PRIMARY KEY,
    ebpf_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ip_or_cidr inet NOT NULL,
    score integer NOT NULL DEFAULT 0,
    action text NOT NULL DEFAULT 'drop',
    source text NOT NULL DEFAULT 'manual',
    rule_id uuid REFERENCES rules(id) ON DELETE SET NULL,
    reason text NOT NULL,
    expires_at timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX manual_blacklist_entries_ip_idx ON manual_blacklist_entries USING gist (ip_or_cidr inet_ops);

CREATE TABLE feed_sources (
    id uuid PRIMARY KEY,
    name text NOT NULL UNIQUE,
    type text NOT NULL,
    url text NOT NULL DEFAULT '',
    credential_ref text NOT NULL DEFAULT '',
    required_for_production boolean NOT NULL DEFAULT false,
    enabled boolean NOT NULL DEFAULT false,
    interval_seconds integer NOT NULL DEFAULT 3600,
    license_note text NOT NULL DEFAULT '',
    quota_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'placeholder',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE policy_snapshots (
    version bigint PRIMARY KEY,
    checksum text NOT NULL,
    object_checksum text NOT NULL,
    snapshot jsonb NOT NULL,
    rollback_from bigint REFERENCES policy_snapshots(version),
    created_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX policy_snapshots_created_at_idx ON policy_snapshots(created_at);
CREATE INDEX policy_snapshots_rollback_from_idx ON policy_snapshots(rollback_from);

CREATE TABLE policy_apply_status (
    id uuid PRIMARY KEY,
    agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    policy_version bigint NOT NULL,
    status text NOT NULL,
    error_stage text NOT NULL DEFAULT '',
    error_reason text NOT NULL DEFAULT '',
    map_stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    devmap_stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    reported_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (agent_id, policy_version)
);
CREATE INDEX policy_apply_status_agent_idx ON policy_apply_status(agent_id, reported_at);

CREATE TABLE audit_events (
    id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor_id uuid REFERENCES app_users(id) ON DELETE SET NULL,
    actor_username text NOT NULL DEFAULT '',
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    before jsonb,
    after jsonb,
    reason text,
    request_id text NOT NULL DEFAULT '',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE audit_events_default PARTITION OF audit_events DEFAULT;
CREATE INDEX audit_events_actor_idx ON audit_events(actor_id, created_at);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type, entity_id, created_at);
`,
	},
	{
		Version: 2,
		Name:    "phase06_observability_events",
		SQL: `
CREATE TABLE security_events (
    id uuid PRIMARY KEY,
    received_at timestamptz NOT NULL DEFAULT now(),
    event_time timestamptz NOT NULL DEFAULT now(),
    agent_id uuid REFERENCES agents(id) ON DELETE SET NULL,
    mono_ts_ns bigint NOT NULL DEFAULT 0,
    policy_version bigint NOT NULL DEFAULT 0,
    src_ip inet NOT NULL,
    src_prefix24 inet NOT NULL,
    dst_ip inet NOT NULL,
    src_port integer NOT NULL DEFAULT 0,
    dst_port integer NOT NULL DEFAULT 0,
    protocol integer NOT NULL DEFAULT 0,
    tcp_flags integer NOT NULL DEFAULT 0,
    action integer NOT NULL DEFAULT 0,
    reason integer NOT NULL DEFAULT 0,
    service_id bigint NOT NULL DEFAULT 0,
    rule_id bigint NOT NULL DEFAULT 0,
    pkt_len integer NOT NULL DEFAULT 0,
    sample_rate integer NOT NULL DEFAULT 1,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX security_events_time_idx ON security_events(event_time DESC);
CREATE INDEX security_events_agent_time_idx ON security_events(agent_id, event_time DESC);
CREATE INDEX security_events_service_time_idx ON security_events(service_id, event_time DESC);
CREATE INDEX security_events_rule_time_idx ON security_events(rule_id, event_time DESC);
CREATE INDEX security_events_action_reason_time_idx ON security_events(action, reason, event_time DESC);
CREATE INDEX security_events_src_ip_time_idx ON security_events(src_ip, event_time DESC);
CREATE INDEX security_events_src_prefix24_time_idx ON security_events(src_prefix24, event_time DESC);
CREATE INDEX security_events_dst_port_time_idx ON security_events(dst_port, event_time DESC);
`,
	},
	{
		Version: 3,
		Name:    "phase07_baseline_anomaly_auto_enforce",
		SQL: `
ALTER TABLE rules
    ADD COLUMN IF NOT EXISTS dimension text NOT NULL DEFAULT 'source_service'
        CHECK (dimension IN ('source', 'service', 'source_service'));

CREATE TABLE baseline_profiles (
    id uuid PRIMARY KEY,
    service_id uuid NOT NULL REFERENCES backend_services(id) ON DELETE CASCADE,
    interface_name text NOT NULL,
    protocol text NOT NULL CHECK (protocol IN ('tcp', 'udp', 'icmp', 'all')),
    port integer NOT NULL DEFAULT 0,
    time_window text NOT NULL DEFAULT '5m',
    expected_pps double precision NOT NULL DEFAULT 0,
    expected_bps double precision NOT NULL DEFAULT 0,
    expected_cps double precision NOT NULL DEFAULT 0,
    history_hours integer NOT NULL DEFAULT 0,
    confidence numeric NOT NULL DEFAULT 0,
    approved boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'draft',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    approved_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    approved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (service_id, interface_name, protocol, port, time_window)
);
CREATE INDEX baseline_profiles_service_idx ON baseline_profiles(service_id, approved, time_window);

CREATE TABLE anomaly_evaluations (
    id uuid PRIMARY KEY,
    service_id uuid REFERENCES backend_services(id) ON DELETE SET NULL,
    baseline_id uuid REFERENCES baseline_profiles(id) ON DELETE SET NULL,
    evaluated_at timestamptz NOT NULL DEFAULT now(),
    time_window text NOT NULL DEFAULT '5m',
    pps double precision NOT NULL DEFAULT 0,
    bps double precision NOT NULL DEFAULT 0,
    cps double precision NOT NULL DEFAULT 0,
    drop_ratio double precision NOT NULL DEFAULT 0,
    score numeric NOT NULL DEFAULT 0,
    confidence numeric NOT NULL DEFAULT 0,
    signals text[] NOT NULL DEFAULT '{}',
    recommendation text NOT NULL DEFAULT 'observe',
    recommended_action text NOT NULL DEFAULT 'rate_limit',
    proposed_ttl_seconds integer NOT NULL DEFAULT 0,
    proposed_rule_id uuid REFERENCES rules(id) ON DELETE SET NULL,
    auto_enforced boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'recorded',
    reason text NOT NULL DEFAULT '',
    source text NOT NULL DEFAULT '',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX anomaly_evaluations_time_idx ON anomaly_evaluations(evaluated_at DESC);
CREATE INDEX anomaly_evaluations_service_time_idx ON anomaly_evaluations(service_id, evaluated_at DESC);
`,
	},
}

func RunMigrations(ctx context.Context, pool *pgxpool.Pool) error {
	if pool == nil {
		return fmt.Errorf("nil pgx pool")
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
    version integer PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now()
)`); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(4100550005)`); err != nil {
		return err
	}
	for _, migration := range Migrations {
		var applied bool
		if err := tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE version = $1)`, migration.Version).Scan(&applied); err != nil {
			return err
		}
		if applied {
			continue
		}
		if _, err := tx.Exec(ctx, migration.SQL); err != nil {
			return fmt.Errorf("migration %d %s: %w", migration.Version, migration.Name, err)
		}
		if _, err := tx.Exec(ctx, `INSERT INTO schema_migrations(version, name) VALUES ($1, $2)`, migration.Version, migration.Name); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}

func AppliedMigrationNames(ctx context.Context, pool *pgxpool.Pool) ([]string, error) {
	rows, err := pool.Query(ctx, `SELECT name FROM schema_migrations ORDER BY version`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		out = append(out, name)
	}
	return out, rows.Err()
}

func SQLMigrationText() string {
	var b strings.Builder
	for _, migration := range Migrations {
		fmt.Fprintf(&b, "-- %03d_%s\n%s\n", migration.Version, migration.Name, migration.SQL)
	}
	return b.String()
}
